[theme]
base = "dark"
primaryColor = "#FFCB1F"
backgroundColor = "#0D141C"
secondaryBackgroundColor = "#151F2A"
textColor = "#EAF2F8"
linkColor = "#45CDFF"
borderColor = "#2D4052"
showWidgetBorder = true
baseRadius = "2px"
buttonRadius = "2px"
font = "'Inter':https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
headingFont = "'IBM Plex Serif':https://fonts.googleapis.com/css2?family=IBM+Plex+Serif:wght@400;500;600&display=swap"
codeFont = "'JetBrains Mono':https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap"
headingFontWeights = [600, 600, 600, 500, 500, 500]
baseFontSize = 15
linkUnderline = false
chartCategoricalColors = ["#45CDFF", "#FFCB1F", "#FF6B42", "#4ADE9B", "#B48BFF"]
showSidebarBorder = true

[theme.sidebar]
backgroundColor = "#080E15"
secondaryBackgroundColor = "#151F2A"
textColor = "#EAF2F8"
borderColor = "#233343"
primaryColor = "#FFCB1F"

[server]
maxUploadSize = 200
enableStaticServing = true

[browser]
gatherUsageStats = false
